/hst:hst/hst:configurations/pactronics-german/hst:workspace/hst:sitemenus/categories/Produkte:
  .meta:order-before: Marken
  jcr:primaryType: hst:sitemenuitem
  jcr:mixinTypes: ['dxphst:mergeable']
  hst:referencesitemapitem: categories/electronics
  hst:repobased: false
