definitions:
  config:
    /hst:hst/hst:hosts/pactronics-poc:
      jcr:primaryType: hst:virtualhostgroup
      /io:
        jcr:primaryType: hst:virtualhost
        hst:scheme: https
        hst:showcontextpath: true
        /onehippo:
          jcr:primaryType: hst:virtualhost
          /${od2_nightly_environment}:
            jcr:primaryType: hst:virtualhost
            /hst:root:
              .meta:residual-child-node-category: content
              jcr:primaryType: hst:mount
              hst:homepage: root
              hst:mountpoint: /hst:pactronics/hst:sites/pactronics
              hst:alias: root
              /rest:
                .meta:residual-child-node-category: content
                jcr:primaryType: hst:mount
                hst:alias: rest
                hst:ismapped: true
                hst:namedpipeline: JaxrsRestPlainPipeline
                hst:nochannelinfo: true
                hst:types: [rest]
              /kiosk:
                .meta:residual-child-node-category: content
                jcr:primaryType: hst:mount
                hst:mountpoint: /hst:pactronics/hst:sites/kioskapp
                hst:namedpipeline: SpaSitePipeline
                hst:pagemodelapi: resourceapi
                hst:responseheaders: ['Access-Control-Allow-Origin: https://pactronics-poc.onehippo.io',
                                      'Access-Control-Allow-Credentials: true']
                hst:homepage: root
              /de:
                .meta:residual-child-node-category: content
                jcr:primaryType: hst:mount
                hst:locale: de_DE
                hst:mountpoint: /hst:pactronics/hst:sites/pactronics-german