definitions:
  config:
    /hst:hst/hst:configurations/common/hst:pages/product-finder:
      jcr:primaryType: hst:component
      hst:referencecomponent: hst:abstractpages/starterstore-base
      /main:
        jcr:primaryType: hst:component
        hst:template: product-finder
