/hst:hst/hst:configurations/external/hst:workspace/hst:pages/product-skf-radial-spherical-plain-bearing-contentpage:
  jcr:primaryType: hst:component
  jcr:mixinTypes: ['dxphst:mergeable']
  hst:lastmodified: 2019-08-13T11:40:24.509+02:00
  hst:referencecomponent: hst:abstractpages/starterstore-base
  /main:
    jcr:primaryType: hst:containercomponent
    jcr:mixinTypes: ['dxphst:mergeable']
    hst:label: Content Page Main
    hst:lastmodified: 2019-08-13T11:40:57.926+02:00
    hst:xtype: hst.vbox
