? /hst:hst/hst:configurations/external/hst:workspace/hst:pages/producten-nivea-3-in-1-verfrissende-reinigingsdoekjes-120092763.html-productpage
: jcr:primaryType: hst:component
  jcr:mixinTypes: ['dxphst:mergeable']
  hst:lastmodified: 2019-08-12T14:06:15.918+02:00
  hst:referencecomponent: hst:abstractpages/starterstore-base
  /main:
    jcr:primaryType: hst:containercomponent
    jcr:mixinTypes: ['dxphst:mergeable', 'hippostd:relaxed']
    hst:label: Content Page Main
    hst:lastmodified: 2019-08-12T14:07:37.464+02:00
    hst:xtype: hst.vbox
    mode: inside
    selector: '#content > div > section:nth-child(3) > div > div'
    /simplecontent:
      jcr:primaryType: hst:containeritemcomponent
      jcr:mixinTypes: ['dxphst:mergeable']
      hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsDocumentComponent
      hst:iconpath: images/essentials/catalog-component-icons/simple-content.png
      hst:label: Simple Content
      hst:parameternames: [com.onehippo.cms7.targeting.TargetingParameterUtil.hide,
        document, org.hippoecm.hst.core.component.template]
      hst:parametervalues: ['off', etos/nail-polish-remover, 'webfile:/freemarker/hstdefault/contentpage-main.ftl']
      hst:template: contentpage-main
      hst:xtype: hst.item
  /bottom:
    jcr:primaryType: hst:containercomponent
    jcr:mixinTypes: ['dxphst:mergeable', 'hippostd:relaxed']
    hst:lastmodified: 2019-08-12T14:07:37.464+02:00
    hst:xtype: HST.vBox
    mode: bottom
    selector: '#content > div > section:nth-child(5) > div'
    /ProductsGrid:
      jcr:primaryType: hst:containeritemcomponent
      jcr:mixinTypes: ['dxphst:mergeable']
      hst:componentclassname: com.bloomreach.commercedxp.starterstore.components.GenericCommandChainComponent
      hst:iconpath: images/essentials/catalog-component-icons/product-grid(search).png
      hst:label: Products Grid
      hst:parameternames: [connectorComponent, starterstoreQueryParam_query, starterstoreQueryParam_currentPage,
        showFacets, com.onehippo.cms7.targeting.TargetingParameterUtil.hide, widgetId,
        showPagination, locale, starterstoreQueryParam_pageSize, commands, org.hippoecm.hst.core.component.template]
      hst:parametersinfoclassname: com.bloomreach.commercedxp.starterstore.components.info.QueryComponentInfo
      hst:parametervalues: [productSearch, trackers, '1', 'off', 'off', '', 'off',
        en, '3', 'customInitContextCommand,cartCreateCommand, cartProductListCommand,
          cartProductAddCommand, personalizationCallCommand, commerceCallCommand,
          pageableCommand', 'webfile:/freemarker/hstdefault/starterstore-productlist.ftl']
      hst:template: starterstore-productlist
      hst:xtype: hst.item
