/hst:hst/hst:configurations/external/hst:workspace/hst:pages/producten-contentpage:
  jcr:primaryType: hst:component
  jcr:mixinTypes: ['dxphst:mergeable']
  hst:lastmodified: 2019-08-12T11:49:22.304+02:00
  hst:referencecomponent: hst:abstractpages/starterstore-base
  /main:
    jcr:primaryType: hst:containercomponent
    jcr:mixinTypes: ['dxphst:mergeable']
    hst:label: Content Page Main
    hst:lastmodified: 2019-08-12T11:49:30.758+02:00
    hst:xtype: hst.vbox
