definitions:
  config:
    /hst:hst/hst:configurations/common-catalog/hst:components/ProductDetail:
      jcr:primaryType: hst:component
      hst:componentclassname: com.bloomreach.commercedxp.starterstore.components.GenericCommandChainComponent
      hst:template: starterstore-productdecorator
