/hst:hst/hst:blueprints/commerce-site/hst:configuration/hst:workspace/hst:sitemenus/footer/Contact us:
  jcr:primaryType: hst:sitemenuitem
  hst:referencesitemapitem: contact-us
  hst:repobased: false
