/hst:hst/hst:blueprints/commerce-site/hst:configuration/hst:workspace/hst:containers/starterstore-base/search/SearchBox:
  jcr:primaryType: hst:containeritemcomponent
  hst:componentclassname: com.bloomreach.commercedxp.starterstore.components.GenericCommandChainComponent
  hst:iconpath: images/essentials/catalog-component-icons/starterstore-bloomreach-dxp.png
  hst:label: Search box
  hst:parameternames: [connectorComponent, connector, enableAutosuggest, commands]
  hst:parametersinfoclassname: com.bloomreach.commercedxp.starterstore.components.info.SearchBoxlComponentInfo
  hst:parametervalues: [autosuggest, '', 'on', 'initContextCommand, bloomreachAutosuggestCallCommand,
      commerceCallCommand']
  hst:resourcetemplate: starterstore-autosuggest
  hst:template: starterstore-searchbox
  hst:xtype: hst.item
