/hst:hst/hst:blueprints/commerce-site/hst:configuration/hst:workspace/hst:sitemenus/footer/Documentation:
  jcr:primaryType: hst:sitemenuitem
  hst:referencesitemapitem: content/documentation.html
  hst:repobased: false
