/hst:hst/hst:blueprints/commerce-site/hst:configuration/hst:workspace/hst:sitemenus/footer/Work with Pactronics:
  .meta:order-before: Privacy Policy
  jcr:primaryType: hst:sitemenuitem
  hst:referencesitemapitem: careers
  hst:repobased: false
