/hst:hst/hst:blueprints/commerce-site/hst:configuration/hst:workspace/hst:sitemenus/main/Articles:
  .meta:order-before: About Us
  jcr:primaryType: hst:sitemenuitem
  hst:referencesitemapitem: articles
  hst:repobased: false
