/hst:hst/hst:blueprints/commerce-site/hst:configuration/hst:workspace/hst:channel/hst:channelinfo:
  jcr:primaryType: hst:channelinfo
  bloomReachApisEnabled: true
  defaultConnector: commercetools
  projectNamespace: pactronics
  universalpixel:acct_id: ${bloomreach.account.id}
  universalpixel:defaultchannelpixelvars: /content/documents/administration/pixel/default-pixel-variables
  universalpixel:disabledinpreview: true
  universalpixel:domain_key: ${bloomreach.domain.key}
  universalpixel:enabled: true
