/hst:hst/hst:configurations/pactronics-german/hst:workspace/hst:sitemap/products:
  jcr:primaryType: hst:sitemapitem
  jcr:mixinTypes: ['dxphst:mergeable']
  hst:componentconfigurationid: hst:pages/starterstore-productsearch
  hst:refId: product
  hst:relativecontentpath: products
  /_default_:
    jcr:primaryType: hst:sitemapitem
    jcr:mixinTypes: ['dxphst:mergeable']
    hst:componentconfigurationid: hst:pages/starterstore-productdecorator
    hst:parameternames: [externalReferenceId]
    hst:parametervalues: ['${1}']
  /stylish-and-ergonomic-laptop-tables:
    jcr:primaryType: hst:sitemapitem
    jcr:mixinTypes: ['dxphst:mergeable']
    hst:componentconfigurationid: hst:pages/stylish-and-ergonomic-laptop-tables-productexperiencepage
    hst:lastmodified: 2018-11-22T13:52:29.397+01:00
    hst:pagetitle: Stylish and Ergonomic Laptop Tables
  /smart-watch-one:
    jcr:primaryType: hst:sitemapitem
    jcr:mixinTypes: ['dxphst:mergeable']
    hst:componentconfigurationid: hst:pages/products-smart-watch-one-productexperiencepage
    hst:lastmodified: 2018-11-29T10:29:52.971+01:00
    hst:pagetitle: Smart Watch One
  /smart-watch-1s:
    jcr:primaryType: hst:sitemapitem
    jcr:mixinTypes: ['dxphst:mergeable']
    hst:componentconfigurationid: hst:pages/products-smart-watch-1s-productexperiencepage
    hst:lastmodified: 2018-11-29T10:30:34.495+01:00
    hst:pagetitle: Smart Watch 1S
  /super-duper-smartwatch:
    jcr:primaryType: hst:sitemapitem
    jcr:mixinTypes: ['dxphst:mergeable']
    hst:componentconfigurationid: hst:pages/products-super-duper-smartwatch-productexperiencepage
    hst:lastmodified: 2019-03-26T10:20:52.129+01:00
    hst:pagetitle: Super duper smartwatch
